name: Build and Test

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
env:
  SOLUTION_FILE: NimblePros.SharedKernel.slnx
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Build
      run: dotnet build "${{ env.SOLUTION_FILE }}" --configuration Release
    - name: Test
      run: dotnet test "${{ env.SOLUTION_FILE }}" --configuration Release --no-build --no-restore
      
