name: Publish to Nuget

on: 
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Build
      run: dotnet build NimblePros.SharedKernel.sln --configuration Release
    - name: Test
      run: dotnet test NimblePros.SharedKernel.sln --configuration Release --no-build --no-restore
    - name: Pack
      run: dotnet pack NimblePros.SharedKernel.sln --configuration Release --no-build --no-restore --output .
    - name: NuGet login (OIDC -> temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
    - name: Push to NuGet
      if: startsWith(github.rf, 'refs/tags/') #only push if building a tag
      shell: pwsh
      run: |
        Get-ChildItem artifacts/package/release -Filter *.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName `
              --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" `
              --source https://api.nuget.org/v3/index.json
          }
